apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gardener-discovery-server
  namespace: gardener-system-shoot-issuer
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
