apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gardener-discovery-server
  namespace: gardener-system-shoot-issuer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gardener-discovery-server
subjects:
- kind: ServiceAccount
  name: gardener-discovery-server
  namespace: garden
