/*
Copyright SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	authentication "github.com/gardener/gardener/pkg/apis/authentication"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWorkloadIdentities implements WorkloadIdentityInterface
type FakeWorkloadIdentities struct {
	Fake *FakeAuthentication
	ns   string
}

var workloadidentitiesResource = authentication.SchemeGroupVersion.WithResource("workloadidentities")

var workloadidentitiesKind = authentication.SchemeGroupVersion.WithKind("WorkloadIdentity")

// Get takes name of the workloadIdentity, and returns the corresponding workloadIdentity object, and an error if there is any.
func (c *FakeWorkloadIdentities) Get(ctx context.Context, name string, options v1.GetOptions) (result *authentication.WorkloadIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workloadidentitiesResource, c.ns, name), &authentication.WorkloadIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authentication.WorkloadIdentity), err
}

// List takes label and field selectors, and returns the list of WorkloadIdentities that match those selectors.
func (c *FakeWorkloadIdentities) List(ctx context.Context, opts v1.ListOptions) (result *authentication.WorkloadIdentityList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workloadidentitiesResource, workloadidentitiesKind, c.ns, opts), &authentication.WorkloadIdentityList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &authentication.WorkloadIdentityList{ListMeta: obj.(*authentication.WorkloadIdentityList).ListMeta}
	for _, item := range obj.(*authentication.WorkloadIdentityList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested workloadIdentities.
func (c *FakeWorkloadIdentities) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workloadidentitiesResource, c.ns, opts))

}

// Create takes the representation of a workloadIdentity and creates it.  Returns the server's representation of the workloadIdentity, and an error, if there is any.
func (c *FakeWorkloadIdentities) Create(ctx context.Context, workloadIdentity *authentication.WorkloadIdentity, opts v1.CreateOptions) (result *authentication.WorkloadIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workloadidentitiesResource, c.ns, workloadIdentity), &authentication.WorkloadIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authentication.WorkloadIdentity), err
}

// Update takes the representation of a workloadIdentity and updates it. Returns the server's representation of the workloadIdentity, and an error, if there is any.
func (c *FakeWorkloadIdentities) Update(ctx context.Context, workloadIdentity *authentication.WorkloadIdentity, opts v1.UpdateOptions) (result *authentication.WorkloadIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workloadidentitiesResource, c.ns, workloadIdentity), &authentication.WorkloadIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authentication.WorkloadIdentity), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWorkloadIdentities) UpdateStatus(ctx context.Context, workloadIdentity *authentication.WorkloadIdentity, opts v1.UpdateOptions) (*authentication.WorkloadIdentity, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(workloadidentitiesResource, "status", c.ns, workloadIdentity), &authentication.WorkloadIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authentication.WorkloadIdentity), err
}

// Delete takes name of the workloadIdentity and deletes it. Returns an error if one occurs.
func (c *FakeWorkloadIdentities) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(workloadidentitiesResource, c.ns, name, opts), &authentication.WorkloadIdentity{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkloadIdentities) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workloadidentitiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &authentication.WorkloadIdentityList{})
	return err
}

// Patch applies the patch and returns the patched workloadIdentity.
func (c *FakeWorkloadIdentities) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *authentication.WorkloadIdentity, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workloadidentitiesResource, c.ns, name, pt, data, subresources...), &authentication.WorkloadIdentity{})

	if obj == nil {
		return nil, err
	}
	return obj.(*authentication.WorkloadIdentity), err
}
