/*
Copyright SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gardener/gardener/pkg/apis/authentication/v1alpha1"
	scheme "github.com/gardener/gardener/pkg/client/authentication/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AdminKubeconfigRequestsGetter has a method to return a AdminKubeconfigRequestInterface.
// A group's client should implement this interface.
type AdminKubeconfigRequestsGetter interface {
	AdminKubeconfigRequests(namespace string) AdminKubeconfigRequestInterface
}

// AdminKubeconfigRequestInterface has methods to work with AdminKubeconfigRequest resources.
type AdminKubeconfigRequestInterface interface {
	Create(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.CreateOptions) (*v1alpha1.AdminKubeconfigRequest, error)
	Update(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.UpdateOptions) (*v1alpha1.AdminKubeconfigRequest, error)
	UpdateStatus(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.UpdateOptions) (*v1alpha1.AdminKubeconfigRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AdminKubeconfigRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AdminKubeconfigRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AdminKubeconfigRequest, err error)
	AdminKubeconfigRequestExpansion
}

// adminKubeconfigRequests implements AdminKubeconfigRequestInterface
type adminKubeconfigRequests struct {
	client rest.Interface
	ns     string
}

// newAdminKubeconfigRequests returns a AdminKubeconfigRequests
func newAdminKubeconfigRequests(c *AuthenticationV1alpha1Client, namespace string) *adminKubeconfigRequests {
	return &adminKubeconfigRequests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the adminKubeconfigRequest, and returns the corresponding adminKubeconfigRequest object, and an error if there is any.
func (c *adminKubeconfigRequests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AdminKubeconfigRequest, err error) {
	result = &v1alpha1.AdminKubeconfigRequest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AdminKubeconfigRequests that match those selectors.
func (c *adminKubeconfigRequests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AdminKubeconfigRequestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AdminKubeconfigRequestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested adminKubeconfigRequests.
func (c *adminKubeconfigRequests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a adminKubeconfigRequest and creates it.  Returns the server's representation of the adminKubeconfigRequest, and an error, if there is any.
func (c *adminKubeconfigRequests) Create(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.CreateOptions) (result *v1alpha1.AdminKubeconfigRequest, err error) {
	result = &v1alpha1.AdminKubeconfigRequest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminKubeconfigRequest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a adminKubeconfigRequest and updates it. Returns the server's representation of the adminKubeconfigRequest, and an error, if there is any.
func (c *adminKubeconfigRequests) Update(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.UpdateOptions) (result *v1alpha1.AdminKubeconfigRequest, err error) {
	result = &v1alpha1.AdminKubeconfigRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		Name(adminKubeconfigRequest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminKubeconfigRequest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *adminKubeconfigRequests) UpdateStatus(ctx context.Context, adminKubeconfigRequest *v1alpha1.AdminKubeconfigRequest, opts v1.UpdateOptions) (result *v1alpha1.AdminKubeconfigRequest, err error) {
	result = &v1alpha1.AdminKubeconfigRequest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		Name(adminKubeconfigRequest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(adminKubeconfigRequest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the adminKubeconfigRequest and deletes it. Returns an error if one occurs.
func (c *adminKubeconfigRequests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *adminKubeconfigRequests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched adminKubeconfigRequest.
func (c *adminKubeconfigRequests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AdminKubeconfigRequest, err error) {
	result = &v1alpha1.AdminKubeconfigRequest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("adminkubeconfigrequests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
