{{- if .Values.global.apiserver.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-apiserver-workload-identity-key
  namespace: garden
  labels:
    app: gardener
    role: apiserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  signingKey: {{ required ".Values.global.apiserver.workloadIdentity.signingKey is required" (b64enc .Values.global.apiserver.workloadIdentity.signingKey) }}
{{- end }}
