apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-openid-discovery
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: openid-discovery
automountServiceAccountToken: false
