//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	authentication "github.com/gardener/gardener/pkg/apis/authentication"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdminKubeconfigRequest)(nil), (*authentication.AdminKubeconfigRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdminKubeconfigRequest_To_authentication_AdminKubeconfigRequest(a.(*AdminKubeconfigRequest), b.(*authentication.AdminKubeconfigRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AdminKubeconfigRequest)(nil), (*AdminKubeconfigRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AdminKubeconfigRequest_To_v1alpha1_AdminKubeconfigRequest(a.(*authentication.AdminKubeconfigRequest), b.(*AdminKubeconfigRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdminKubeconfigRequestSpec)(nil), (*authentication.AdminKubeconfigRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec(a.(*AdminKubeconfigRequestSpec), b.(*authentication.AdminKubeconfigRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AdminKubeconfigRequestSpec)(nil), (*AdminKubeconfigRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec(a.(*authentication.AdminKubeconfigRequestSpec), b.(*AdminKubeconfigRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AdminKubeconfigRequestStatus)(nil), (*authentication.AdminKubeconfigRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus(a.(*AdminKubeconfigRequestStatus), b.(*authentication.AdminKubeconfigRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.AdminKubeconfigRequestStatus)(nil), (*AdminKubeconfigRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus(a.(*authentication.AdminKubeconfigRequestStatus), b.(*AdminKubeconfigRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TokenRequest)(nil), (*authentication.TokenRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TokenRequest_To_authentication_TokenRequest(a.(*TokenRequest), b.(*authentication.TokenRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.TokenRequest)(nil), (*TokenRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_TokenRequest_To_v1alpha1_TokenRequest(a.(*authentication.TokenRequest), b.(*TokenRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TokenRequestRequestSpec)(nil), (*authentication.TokenRequestRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec(a.(*TokenRequestRequestSpec), b.(*authentication.TokenRequestRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.TokenRequestRequestSpec)(nil), (*TokenRequestRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec(a.(*authentication.TokenRequestRequestSpec), b.(*TokenRequestRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TokenRequestStatus)(nil), (*authentication.TokenRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus(a.(*TokenRequestStatus), b.(*authentication.TokenRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.TokenRequestStatus)(nil), (*TokenRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus(a.(*authentication.TokenRequestStatus), b.(*TokenRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentity)(nil), (*authentication.WorkloadIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentity_To_authentication_WorkloadIdentity(a.(*WorkloadIdentity), b.(*authentication.WorkloadIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WorkloadIdentity)(nil), (*WorkloadIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WorkloadIdentity_To_v1alpha1_WorkloadIdentity(a.(*authentication.WorkloadIdentity), b.(*WorkloadIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentityList)(nil), (*authentication.WorkloadIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentityList_To_authentication_WorkloadIdentityList(a.(*WorkloadIdentityList), b.(*authentication.WorkloadIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WorkloadIdentityList)(nil), (*WorkloadIdentityList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WorkloadIdentityList_To_v1alpha1_WorkloadIdentityList(a.(*authentication.WorkloadIdentityList), b.(*WorkloadIdentityList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentitySpec)(nil), (*authentication.WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec(a.(*WorkloadIdentitySpec), b.(*authentication.WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WorkloadIdentitySpec)(nil), (*WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec(a.(*authentication.WorkloadIdentitySpec), b.(*WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentityStatus)(nil), (*authentication.WorkloadIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus(a.(*WorkloadIdentityStatus), b.(*authentication.WorkloadIdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authentication.WorkloadIdentityStatus)(nil), (*WorkloadIdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus(a.(*authentication.WorkloadIdentityStatus), b.(*WorkloadIdentityStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdminKubeconfigRequest_To_authentication_AdminKubeconfigRequest(in *AdminKubeconfigRequest, out *authentication.AdminKubeconfigRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AdminKubeconfigRequest_To_authentication_AdminKubeconfigRequest is an autogenerated conversion function.
func Convert_v1alpha1_AdminKubeconfigRequest_To_authentication_AdminKubeconfigRequest(in *AdminKubeconfigRequest, out *authentication.AdminKubeconfigRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdminKubeconfigRequest_To_authentication_AdminKubeconfigRequest(in, out, s)
}

func autoConvert_authentication_AdminKubeconfigRequest_To_v1alpha1_AdminKubeconfigRequest(in *authentication.AdminKubeconfigRequest, out *AdminKubeconfigRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_AdminKubeconfigRequest_To_v1alpha1_AdminKubeconfigRequest is an autogenerated conversion function.
func Convert_authentication_AdminKubeconfigRequest_To_v1alpha1_AdminKubeconfigRequest(in *authentication.AdminKubeconfigRequest, out *AdminKubeconfigRequest, s conversion.Scope) error {
	return autoConvert_authentication_AdminKubeconfigRequest_To_v1alpha1_AdminKubeconfigRequest(in, out, s)
}

func autoConvert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec(in *AdminKubeconfigRequestSpec, out *authentication.AdminKubeconfigRequestSpec, s conversion.Scope) error {
	if err := v1.Convert_Pointer_int64_To_int64(&in.ExpirationSeconds, &out.ExpirationSeconds, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec(in *AdminKubeconfigRequestSpec, out *authentication.AdminKubeconfigRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdminKubeconfigRequestSpec_To_authentication_AdminKubeconfigRequestSpec(in, out, s)
}

func autoConvert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec(in *authentication.AdminKubeconfigRequestSpec, out *AdminKubeconfigRequestSpec, s conversion.Scope) error {
	if err := v1.Convert_int64_To_Pointer_int64(&in.ExpirationSeconds, &out.ExpirationSeconds, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec is an autogenerated conversion function.
func Convert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec(in *authentication.AdminKubeconfigRequestSpec, out *AdminKubeconfigRequestSpec, s conversion.Scope) error {
	return autoConvert_authentication_AdminKubeconfigRequestSpec_To_v1alpha1_AdminKubeconfigRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus(in *AdminKubeconfigRequestStatus, out *authentication.AdminKubeconfigRequestStatus, s conversion.Scope) error {
	out.Kubeconfig = *(*[]byte)(unsafe.Pointer(&in.Kubeconfig))
	out.ExpirationTimestamp = in.ExpirationTimestamp
	return nil
}

// Convert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus is an autogenerated conversion function.
func Convert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus(in *AdminKubeconfigRequestStatus, out *authentication.AdminKubeconfigRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdminKubeconfigRequestStatus_To_authentication_AdminKubeconfigRequestStatus(in, out, s)
}

func autoConvert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus(in *authentication.AdminKubeconfigRequestStatus, out *AdminKubeconfigRequestStatus, s conversion.Scope) error {
	out.Kubeconfig = *(*[]byte)(unsafe.Pointer(&in.Kubeconfig))
	out.ExpirationTimestamp = in.ExpirationTimestamp
	return nil
}

// Convert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus is an autogenerated conversion function.
func Convert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus(in *authentication.AdminKubeconfigRequestStatus, out *AdminKubeconfigRequestStatus, s conversion.Scope) error {
	return autoConvert_authentication_AdminKubeconfigRequestStatus_To_v1alpha1_AdminKubeconfigRequestStatus(in, out, s)
}

func autoConvert_v1alpha1_TokenRequest_To_authentication_TokenRequest(in *TokenRequest, out *authentication.TokenRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TokenRequest_To_authentication_TokenRequest is an autogenerated conversion function.
func Convert_v1alpha1_TokenRequest_To_authentication_TokenRequest(in *TokenRequest, out *authentication.TokenRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_TokenRequest_To_authentication_TokenRequest(in, out, s)
}

func autoConvert_authentication_TokenRequest_To_v1alpha1_TokenRequest(in *authentication.TokenRequest, out *TokenRequest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_TokenRequest_To_v1alpha1_TokenRequest is an autogenerated conversion function.
func Convert_authentication_TokenRequest_To_v1alpha1_TokenRequest(in *authentication.TokenRequest, out *TokenRequest, s conversion.Scope) error {
	return autoConvert_authentication_TokenRequest_To_v1alpha1_TokenRequest(in, out, s)
}

func autoConvert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec(in *TokenRequestRequestSpec, out *authentication.TokenRequestRequestSpec, s conversion.Scope) error {
	if err := v1.Convert_Pointer_int64_To_int64(&in.ExpirationSeconds, &out.ExpirationSeconds, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec is an autogenerated conversion function.
func Convert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec(in *TokenRequestRequestSpec, out *authentication.TokenRequestRequestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TokenRequestRequestSpec_To_authentication_TokenRequestRequestSpec(in, out, s)
}

func autoConvert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec(in *authentication.TokenRequestRequestSpec, out *TokenRequestRequestSpec, s conversion.Scope) error {
	if err := v1.Convert_int64_To_Pointer_int64(&in.ExpirationSeconds, &out.ExpirationSeconds, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec is an autogenerated conversion function.
func Convert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec(in *authentication.TokenRequestRequestSpec, out *TokenRequestRequestSpec, s conversion.Scope) error {
	return autoConvert_authentication_TokenRequestRequestSpec_To_v1alpha1_TokenRequestRequestSpec(in, out, s)
}

func autoConvert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus(in *TokenRequestStatus, out *authentication.TokenRequestStatus, s conversion.Scope) error {
	out.Token = in.Token
	out.ExpirationTimestamp = in.ExpirationTimestamp
	return nil
}

// Convert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus is an autogenerated conversion function.
func Convert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus(in *TokenRequestStatus, out *authentication.TokenRequestStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TokenRequestStatus_To_authentication_TokenRequestStatus(in, out, s)
}

func autoConvert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus(in *authentication.TokenRequestStatus, out *TokenRequestStatus, s conversion.Scope) error {
	out.Token = in.Token
	out.ExpirationTimestamp = in.ExpirationTimestamp
	return nil
}

// Convert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus is an autogenerated conversion function.
func Convert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus(in *authentication.TokenRequestStatus, out *TokenRequestStatus, s conversion.Scope) error {
	return autoConvert_authentication_TokenRequestStatus_To_v1alpha1_TokenRequestStatus(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentity_To_authentication_WorkloadIdentity(in *WorkloadIdentity, out *authentication.WorkloadIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_WorkloadIdentity_To_authentication_WorkloadIdentity is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentity_To_authentication_WorkloadIdentity(in *WorkloadIdentity, out *authentication.WorkloadIdentity, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentity_To_authentication_WorkloadIdentity(in, out, s)
}

func autoConvert_authentication_WorkloadIdentity_To_v1alpha1_WorkloadIdentity(in *authentication.WorkloadIdentity, out *WorkloadIdentity, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_WorkloadIdentity_To_v1alpha1_WorkloadIdentity is an autogenerated conversion function.
func Convert_authentication_WorkloadIdentity_To_v1alpha1_WorkloadIdentity(in *authentication.WorkloadIdentity, out *WorkloadIdentity, s conversion.Scope) error {
	return autoConvert_authentication_WorkloadIdentity_To_v1alpha1_WorkloadIdentity(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentityList_To_authentication_WorkloadIdentityList(in *WorkloadIdentityList, out *authentication.WorkloadIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]authentication.WorkloadIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_WorkloadIdentityList_To_authentication_WorkloadIdentityList is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentityList_To_authentication_WorkloadIdentityList(in *WorkloadIdentityList, out *authentication.WorkloadIdentityList, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentityList_To_authentication_WorkloadIdentityList(in, out, s)
}

func autoConvert_authentication_WorkloadIdentityList_To_v1alpha1_WorkloadIdentityList(in *authentication.WorkloadIdentityList, out *WorkloadIdentityList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]WorkloadIdentity)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_authentication_WorkloadIdentityList_To_v1alpha1_WorkloadIdentityList is an autogenerated conversion function.
func Convert_authentication_WorkloadIdentityList_To_v1alpha1_WorkloadIdentityList(in *authentication.WorkloadIdentityList, out *WorkloadIdentityList, s conversion.Scope) error {
	return autoConvert_authentication_WorkloadIdentityList_To_v1alpha1_WorkloadIdentityList(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec(in *WorkloadIdentitySpec, out *authentication.WorkloadIdentitySpec, s conversion.Scope) error {
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	return nil
}

// Convert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec(in *WorkloadIdentitySpec, out *authentication.WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentitySpec_To_authentication_WorkloadIdentitySpec(in, out, s)
}

func autoConvert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec(in *authentication.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	return nil
}

// Convert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec is an autogenerated conversion function.
func Convert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec(in *authentication.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_authentication_WorkloadIdentitySpec_To_v1alpha1_WorkloadIdentitySpec(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus(in *WorkloadIdentityStatus, out *authentication.WorkloadIdentityStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus(in *WorkloadIdentityStatus, out *authentication.WorkloadIdentityStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentityStatus_To_authentication_WorkloadIdentityStatus(in, out, s)
}

func autoConvert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus(in *authentication.WorkloadIdentityStatus, out *WorkloadIdentityStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	return nil
}

// Convert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus is an autogenerated conversion function.
func Convert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus(in *authentication.WorkloadIdentityStatus, out *WorkloadIdentityStatus, s conversion.Scope) error {
	return autoConvert_authentication_WorkloadIdentityStatus_To_v1alpha1_WorkloadIdentityStatus(in, out, s)
}
